### ISSUE TITLE
Image embeds have wrong size

### ISSUE THREAD

**Issue by niZyalB** [torikushiii/DiscordTwitterBot#1]
For some reason the bot generates the embeds of twitter posts containing images wrong. The images in those embeds would display in wrong sizes.

example: https://imgur.com/a/C4mydm9

clicking on those images would show the full image preview thought.

**Comment by torikushiii** [comment]
thanks for the issue, I already take a look at it and should be fixed now.

**Comment by torikushiii** [comment]
After I take a look and try on another tweet, it seems that the issue still persist, I'll investigate wether this is embed issue or Discord

**Comment by torikushiii** [comment]
issue should be fixed, and all embed image should be display correctly now.
