### ISSUE TITLE
Problem with auth.js

### ISSUE THREAD

**Issue by Chadoxi** [torikushiii/DiscordTwitterBot#3]
![image](https://github.com/torikushiii/DiscordTwitterBot/assets/65661361/c9508c5c-db82-4a96-85e5-045e4afb4d87)
Hey, I have a problem, I need a auth.js file but I don"t have this :/

**Comment by torikushiii** [comment]
yes, this was intended because auth codebase is currently in-progress and it requires tons of guest tokens to make this timeline scraper work

**Comment by Chadoxi** [comment]
> yes, this was intended because auth codebase is currently in-progress and it requires tons of guest tokens to make this timeline scraper work

Oh okay, when the working code will be code source? Or how can qi make "tons of guest tokens"?

**Comment by torikushiii** [comment]
for guest tokens you can see reference on this [issue](https://github.com/zedeus/nitter/issues/983#issuecomment-1681199357) but they limit on how many guest accounts you can create per-day, and for the source, I'll try to release it when Twitter/X stop patching the workarounds

**Comment by Chadoxi** [comment]
Okay I will try thanks!
